class Link:
    def __init__(
        self,
        url: str,
        comes_from: str | None,
        yank_reason: str | None,
        requires_python: str | None,
        hashes: dict[str, str] | None,
        dist_metadata: dict[str, str] | bool | None,
    ) -> None: ...
    @property
    def url_without_fragment(self) -> str: ...
    @property
    def redacted(self) -> str: ...
    @property
    def is_file(self) -> bool: ...
    @property
    def file_path(self) -> str: ...
    @classmethod
    def from_path(cls, path: str) -> Link: ...
    @property
    def is_vcs(self) -> bool: ...
    @property
    def is_yanked(self) -> bool: ...
    @property
    def filename(self) -> str: ...
    @property
    def is_wheel(self) -> bool: ...
    @property
    def subdirectory(self) -> str | None: ...
    @property
    def hashes(self) -> dict[str, str] | None: ...
    @property
    def hash_options(self) -> dict[str, list[str]] | None: ...
    @property
    def dist_metadata_link(self) -> Link | None: ...
